 CREATE TABLE answers (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  answer VARCHAR(255)
);
INSERT INTO answers 
  (answer) 
VALUES 
  ('India'),
  ('Toy Story'),
  ('De Kolonisten van Catan'),
  ('Jan Kooijman'),
  ('De Fuhrer'),
  ('Daphne Deckers'),
  ('De Bermuda Driehoek'),
  ('The First Lady'),
  ('Dommelsch'),
  ('Socrates'),
  ('Playboy'),
  ('De Apenheul'),
  ('Garfield'),
  ('Bryan Adams'),
  ('De Marathon Rotterdam'),
  ('Adam en Eva'),
  ('Vlissingen'),
  ('Bol.com'),
  ('Braveheart'),
  ('Koos Alberts'),
  ('Suske'),
  ('Sony Ericsson'),
  ('Prins Carnaval'),
  ('Montmartre'),
  ('Wim T. Schippers'),
  ('Hongkong'),
  ('Linda'),
  ('Ieniemienie'),
  ('Rush Hour'),
  ('Loretta Schrijver'),
  ('Kate Winslet'),
  ('007'),
  ('Center Parcs'),
  ('Sonja Barend'),
  ('Het Pentagon'),
  ('Disney World'),
  ('Risk'),
  ('Eddy Zoey'),
  ('Delilah'),
  ('Jean-Claude van Damme'),
  ('KLM'),
  ('Columbus'),
  ('Zaandam'),
  ('Ciske de Rat'),
  ('Jack Johnson'),
  ('De Noordpool'),
  ('Giel Beelen'),
  ('AZ'),
  ('Zumba'),
  ('De swastika'),
  ('De Nederlandse Antillen'),
  ('Toy Story 3'),
  ('Het WNF'),
  ('De Volkswagen Kever'),
  ('Sacha de Boer'),
  ('Bruce Willis'),
  ('Met de vlam in de pijp'),
  ('Urk'),
  ('Robijn'),
  ('Leon de Winter'),
  ('Nederland'),
  ('Venz'),
  ('Annie M.G. Schmidt'),
  ('We Will Rock You'),
  ('Charlie Sheen'),
  ('Harry Potter'),
  ('Sony'),
  ('Texas'),
  ('Multatuli'),
  ('Leona Lewis'),
  ('De Europese Unie'),
  ('Eindhoven Airport'),
  ('Serena Williams'),
  ('Viva Hollandia'),
  ('Anthony Hopkins'),
  ('Zweden'),
  ('Pictionary'),
  ('Sinds een dag of twee'),
  ('Mario Been'),
  ('Urbanus'),
  ('Zwitserland'),
  ('Anita Witzier'),
  ('Harrods'),
  ('Cleopatra'),
  ('De Bijlmerramp'),
  ('Toyota'),
  ('Minnie Mouse'),
  ('De Vrije Universiteit'),
  ('Kuala Lumpur'),
  ('De Zangeres Zonder Naam'),
  ('Het Rijksmuseum'),
  ('Willeke Alberti'),
  ('Casanova'),
  ('Ziggo'),
  ('Johan Vlemmix'),
  ('Gordon'),
  ('De Rotterdamse Haven'),
  ('Brainpower'),
  ('Bridget Jones'),
  ('Henry Ford');
